name: Test
on: push
jobs:
  test-job:
    - name: Get code
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install deps
      run: npm ci
    - name: Run tests
      run: npm run test